### ISSUE TITLE
wrong formatting

### ISSUE THREAD

**Issue by ggrigorov** [cweijan/autohotkey-plus#67] opened 2021-02-05 14:00 UTC
v.2.6.2

![image](https://user-images.githubusercontent.com/4126064/107043104-33340000-67cb-11eb-975f-16376911b50c.png)

**Comment by fade2gray** [comment] 2021-02-05 14:50
I can't reproduce it in any shape or form as shown in the image, except if typed in deliberately, and if I use `Format Document`, it corrects it properly.

Are 116 and 118 actually a matched pair of opening and closing braces - could you have a missing brace elsewhere in your code?

**Comment by fade2gray** [comment] 2021-02-05 15:22
![format](https://user-images.githubusercontent.com/1332009/107052658-d550e980-67c5-11eb-8bf1-012539b2c29b.gif)

**Comment by ggrigorov** [comment] 2021-02-07 18:43
Hello @fade2gray,

there it is what I manage to find

let me know if this helps :)

![FXHINVhunK](https://user-images.githubusercontent.com/4126064/107156127-1fcc9480-6985-11eb-96db-cc76f2e7b738.gif)

**Comment by ggrigorov** [comment] 2021-02-07 18:44
`funcThatAffectTheNextOne(dir, def = "") {
    ; switch dir
    ; {
    ; case "case1":
    ;     ret := 1 
    ; Default:
    ;     ret := 2
    ; }

    return ret
}

mainFuncToObserve(wid, path, debug = false)
{
    ; TEST
    If (lvl < minLevel)
    {
        Return False
    }

    return anything
}`

**Comment by fade2gray** [comment] 2021-02-07 20:21
Yep, I see the same. It could be related to this > https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/pull/32

**Comment by mark-wiemer** [comment] 2021-02-07 22:48
There is an open issue for switch-case formatting on my fork: [mark-wiemer#28](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/28), I'm pretty sure this issue has the same root cause, but not 100%. Best way to ensure it gets fixed on my fork is to [open a new issue on my fork](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/new?assignees=mark-wiemer&labels=bug&template=bug_report.md&title=)

**Comment by mark-wiemer** [comment] 2021-02-07 22:51
And @ggrigorov, you can use triple backtick (```) as a code fence to a block of code. Optionally, you can follow it with a language for color highlighting:

    ```autohotkey
    funcThatAffectTheNextOne(dir, def = "") {
    ; switch dir
    ; {
    ; case "case1":
    ; ret := 1
    ; Default:
    ; ret := 2
    ; }
    
    return ret
    }
    
    mainFuncToObserve(wid, path, debug = false)
    {
    ; TEST
    If (lvl < minLevel)
    {
    Return False
    }
    
    return anything
    }
    ```

becomes

```autohotkey
funcThatAffectTheNextOne(dir, def = "") {
; switch dir
; {
; case "case1":
; ret := 1
; Default:
; ret := 2
; }

return ret
}

mainFuncToObserve(wid, path, debug = false)
{
; TEST
If (lvl < minLevel)
{
Return False
}

return anything
}
```

**Comment by mark-wiemer** [comment] 2021-03-03 04:44
Noting here that this is fixed on my extension, [AutoHotkey Plus Plus](https://marketplace.visualstudio.com/items?itemName=mark-wiemer.vscode-autohotkey-plus-plus)

**Comment by mark-wiemer** [comment] 2022-11-23 09:54
Fixed in v3

**Closed as completed by mark-wiemer** 2022-11-23 09:54 UTC
